# Generated by Django 5.2.15 on 2026-06-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Rule name')),
                ('start_date', models.DateField(blank=True, help_text='Inclusive. Empty means no lower limit.', null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='Inclusive. Empty means still active.', null=True, verbose_name='End date')),
                ('hospital_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hospital selling price')),
                ('factory_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Factory purchase price')),
                ('expiration_discount_rate', models.DecimalField(decimal_places=4, default=0, help_text='Example: 0.30 means 30% discount, i.e. 70% final price.', max_digits=5, verbose_name='Expiration discount rate')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave empty only if this rule applies to any product category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='products.productcategory', verbose_name='Product category')),
                ('factory', models.ForeignKey(blank=True, help_text='Leave empty only if this rule applies to any factory.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='factories.factory', verbose_name='Factory')),
            ],
            options={
                'verbose_name': 'Price Policy',
                'verbose_name_plural': 'Price Policies',
                'ordering': ['factory__name', 'category__name', '-start_date'],
            },
        ),
    ]
