# Generated by Django 5.2.15 on 2026-07-14 03:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('pricing', '0001_initial'),
        ('products', '0012_link_unlinked_factory_nodes_with_unique_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepolicy',
            name='expiration_threshold_days',
            field=models.PositiveIntegerField(default=365, help_text='例如 365 表示有效期距离基准日期不足 365 天时应用临期折扣。', verbose_name='Expiration threshold days'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.ForeignKey(blank=True, help_text='留空表示适用于该工厂下所有产品。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='products.productcategory', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='end_date',
            field=models.DateField(blank=True, help_text='包含该日期。留空表示长期有效。', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='expiration_discount_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='0.30 表示优惠 30%，最终支付原价的 70%。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Expiration discount rate'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='留空表示全局通用规则。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='factories.factory', verbose_name='Factory'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='factory_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Factory purchase price'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='hospital_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Hospital selling price'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='start_date',
            field=models.DateField(blank=True, help_text='包含该日期。留空表示无下限。', null=True, verbose_name='Start date'),
        ),
    ]
