# Generated by Django 5.2.15 on 2026-06-09 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='产品编号，例如 BMA-2.5010。', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='产品描述。')),
                ('hospital_unit_price', models.DecimalField(decimal_places=2, default=Decimal('270.00'), help_text='卖给医院的单价。', max_digits=10)),
                ('factory_unit_price', models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='从工厂采购的单价。当前规则通常为 120.00。', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
