# Generated by Django 5.2.15 on 2026-06-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='产品所属供应商 / 工厂。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='factories.factory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, help_text='产品编号，例如 BMA-2.2510。', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory_unit_price',
            field=models.DecimalField(decimal_places=2, default=120, help_text='从工厂采购的单价。', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称。', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='上级分类。没有上级时表示一级科室。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='产品分类，例如 心血管外周 / SINOMED / 支架。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
    ]
