# Generated by Django 5.2.15 on 2026-06-11 08:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_factory_alter_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='factory',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='产品编号，例如 BMA-2.5010。', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='从工厂采购的单价。当前规则通常为 120.00。', max_digits=10),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
