# Generated by Django 5.2.15 on 2026-06-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_factory_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrowsercategory',
            options={'verbose_name': 'Product record', 'verbose_name_plural': 'Product record'},
        ),
    ]
