# Generated by Django 5.2.15 on 2026-06-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productbrowsercategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrowsercategory',
            options={'verbose_name': 'Product records', 'verbose_name_plural': 'Product records'},
        ),
    ]
