# Generated by Django 5.2.15 on 2026-06-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('factory_confirmations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryconfirmation',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='匹配到的工厂库记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_confirmations', to='factories.factory'),
        ),
        migrations.AddField(
            model_name='factoryconfirmation',
            name='factory_match_message',
            field=models.TextField(blank=True, help_text='工厂匹配说明。如果需要人工确认，会写在这里。'),
        ),
        migrations.AddField(
            model_name='factoryconfirmation',
            name='factory_match_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('ok', 'OK'), ('needs_review', 'Needs review'), ('manually_confirmed', 'Manually confirmed')], default='not_checked', help_text='工厂匹配状态。', max_length=50),
        ),
    ]
