# Generated by Django 5.2.15 on 2026-07-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_confirmations', '0004_factoryconfirmation_confirmation_type'),
        ('orders', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial_items', to='orders.order'),
        ),
    ]
