# Generated by Django 5.2.15 on 2026-07-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_confirmations', '0005_alter_serialitem_order'),
        ('orders', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryconfirmation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_confirmations', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='serialitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_items', to='orders.order'),
        ),
    ]
