# Generated by Django 5.2.15 on 2026-06-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_factoryorderrequestdocument'),
        ('orders', '0007_orderitem_expiration_discount_rate_and_more'),
        ('shipments', '0005_shipmentbatch_validated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWorkflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('pending', '待处理'), ('ready_to_generate', '可以生成'), ('generated', '已生成'), ('blocked', '阻塞'), ('cancelled', '取消')], default='pending', max_length=30, verbose_name='流程状态')),
                ('validation_status', models.CharField(choices=[('not_validated', '未校验'), ('ready', '可以生成'), ('needs_review', '需要人工检查'), ('blocked', '禁止生成')], default='not_validated', max_length=30, verbose_name='校验状态')),
                ('validation_data', models.JSONField(blank=True, null=True, verbose_name='校验结果')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='校验时间')),
                ('invoice_status', models.CharField(choices=[('not_generated', '未生成'), ('generated', '已生成'), ('failed', '生成失败')], default='not_generated', max_length=30, verbose_name='Invoice 状态')),
                ('po_status', models.CharField(choices=[('not_generated', '未生成'), ('generated', '已生成'), ('failed', '生成失败')], default='not_generated', max_length=30, verbose_name='Factory PO 状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invoice_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_workflow_items', to='documents.generateddocument', verbose_name='Invoice 文件')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_workflow_items', to='orders.order', verbose_name='订单')),
                ('po_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_workflow_items', to='documents.generateddocument', verbose_name='Factory PO 文件')),
                ('shipment_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_workflow_item', to='shipments.shipmentbatch', verbose_name='发货批次')),
            ],
            options={
                'verbose_name': '待处理文件',
                'verbose_name_plural': '待处理文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
