# Generated by Django 5.2.15 on 2026-06-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_confirmations', '0003_factoryconfirmation_bon_de_commande_manual_confirmed_and_more'),
        ('orders', '0006_order_factory_order_factory_match_message_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(default=1)),
                ('batch_date', models.DateField(blank=True, help_text='Usually factory confirmation shipping_date.', null=True)),
                ('month_key', models.CharField(db_index=True, help_text='YYYY-MM, used as virtual month folder.', max_length=7)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('complete', 'Complete'), ('over_shipped', 'Over shipped'), ('needs_review', 'Needs review')], default='needs_review', max_length=30)),
                ('total_requested_quantity', models.PositiveIntegerField(default=0)),
                ('shipped_this_batch_quantity', models.PositiveIntegerField(default=0)),
                ('total_shipped_after_batch_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_after_batch_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory_confirmation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_batch', to='factory_confirmations.factoryconfirmation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_batches', to='orders.order')),
            ],
            options={
                'verbose_name': 'Shipment Batch',
                'verbose_name_plural': 'Shipment Batches',
                'ordering': ['-batch_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BackorderSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('requested_quantity', models.PositiveIntegerField(default=0)),
                ('shipped_before_batch_quantity', models.PositiveIntegerField(default=0)),
                ('shipped_this_batch_quantity', models.PositiveIntegerField(default=0)),
                ('total_shipped_after_batch_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('is_over_shipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorder_items', to='shipments.shipmentbatch')),
            ],
            options={
                'verbose_name': 'Backorder Snapshot Item',
                'verbose_name_plural': 'Backorder Snapshot Items',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('shipped_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipped_items', to='shipments.shipmentbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Shipped Item',
                'verbose_name_plural': 'Shipped Items',
                'ordering': ['product_code'],
            },
        ),
    ]
