# Generated by Django 5.2.15 on 2026-06-25 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backorders', '0003_inventoryallocation_inventoryitem_allocation'),
        ('shipments', '0002_shipmentmonth_shipmentorderfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbatch',
            name='inventory_allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_batch', to='backorders.inventoryallocation', verbose_name='库存预留记录'),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='source_type',
            field=models.CharField(choices=[('factory_confirmation', '工厂确认文件'), ('inventory_allocation', '库存分配'), ('manual', '人工记录')], default='factory_confirmation', max_length=40, verbose_name='来源类型'),
        ),
    ]
