# Generated by Django 5.2.15 on 2026-06-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_confirmations', '0004_factoryconfirmation_confirmation_type'),
        ('shipments', '0003_shipmentbatch_inventory_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbatch',
            name='factory_confirmation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_batch', to='factory_confirmations.factoryconfirmation', verbose_name='工厂确认文件'),
        ),
    ]
