# Generated by Django 5.2.15 on 2026-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipmentbatch_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbatch',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tracking number'),
        ),
    ]
