# Generated by Django 5.2.15 on 2026-10-08 12:25

import administrative_expenses.models
import administrative_expenses.storage
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Employee salaries'), ('benefits', 'Employee benefits'), ('office_supplies', 'Office supplies'), ('premises', 'Company premises'), ('reimbursement', 'Reimbursements')], max_length=32, verbose_name='Category')),
                ('subcategory', models.CharField(blank=True, default='', max_length=32, verbose_name='Subcategory')),
                ('expense_date', models.DateField(verbose_name='Expense date')),
                ('employee_or_payee', models.CharField(blank=True, max_length=200, verbose_name='Employee / payee')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (EUR)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=8, verbose_name='Payment status')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_expenses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdministrativeExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, storage=administrative_expenses.storage.PrivateExpenseStorage(), upload_to=administrative_expenses.models.attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('payslip', 'Payslip'), ('contract', 'Contract'), ('payment_proof', 'Payment proof'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='administrative_expenses.administrativeexpense')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_expense_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='administrativeexpense',
            index=models.Index(fields=['expense_date', 'is_void'], name='admin_expense_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='administrativeexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='admin_expense_positive'),
        ),
        migrations.AddConstraint(
            model_name='administrativeexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['salary', 'office_supplies', 'premises']), ('subcategory', '')), models.Q(('category', 'benefits'), ('subcategory__in', ['bonus', 'meals', 'transport', 'commission', 'housing', 'holiday_gifts'])), models.Q(('category', 'reimbursement'), ('subcategory__in', ['travel', 'entertainment', 'gifts'])), _connector='OR'), name='admin_expense_category'),
        ),
        migrations.AddConstraint(
            model_name='administrativeexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', True), ('payment_status', 'pending')), models.Q(('paid_at__isnull', False), ('payment_status', 'paid')), _connector='OR'), name='admin_expense_payment'),
        ),
        migrations.AddConstraint(
            model_name='administrativeexpense',
            constraint=models.CheckConstraint(condition=models.Q(('paid_at__isnull', True), ('paid_at__gte', models.F('expense_date')), _connector='OR'), name='admin_expense_paid_date'),
        ),
    ]
