# Generated by Django 5.2.15 on 2026-10-08 12:32

import administrative_expenses.models
import administrative_expenses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeexpenseattachment',
            name='file',
            field=models.FileField(max_length=200, storage=administrative_expenses.storage.PrivateExpenseStorage(), unique=True, upload_to=administrative_expenses.models.attachment_path),
        ),
    ]
