# Generated by Django 5.2.15 on 2026-06-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_orderitem_expiration_discount_rate_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackorderRootFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('backorder_orders', '待发产品'), ('expected_shipping', '预计可发产品')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backorder Library',
                'verbose_name_plural': 'Backorder Library',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedShippingMonthFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('total_remaining_quantity', models.PositiveIntegerField(default=0)),
                ('sort_order', models.CharField(default='9999-99', max_length=20)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expected Shipping Month',
                'verbose_name_plural': 'Expected Shipping Months',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BackorderOrderFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('remaining_total_quantity', models.PositiveIntegerField(default=0)),
                ('earliest_expected_shipping_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True means this order still has remaining products.')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backorder_folder', to='orders.order')),
            ],
            options={
                'verbose_name': 'Backorder Order Folder',
                'verbose_name_plural': 'Backorder Orders',
                'ordering': ['order__bon_de_commande'],
            },
        ),
        migrations.CreateModel(
            name='BackorderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('requested_quantity', models.PositiveIntegerField(default=0)),
                ('shipped_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('expected_shipping_date', models.DateField(blank=True, help_text='Manually entered expected shipping date.', null=True, verbose_name='Expected shipping date')),
                ('expected_shipping_note', models.TextField(blank=True, default='', verbose_name='Expected shipping note')),
                ('expected_month_key', models.CharField(db_index=True, default='no_date', help_text='YYYY-MM or no_date.', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Planned'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='False when this line is fully shipped.')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorder_lines', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('order_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backorders.backorderorderfolder')),
            ],
            options={
                'verbose_name': 'Backorder Line',
                'verbose_name_plural': 'Backorder Lines',
                'ordering': ['order__bon_de_commande', 'product_code'],
                'unique_together': {('order', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='ExpectedShippingProductFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_remaining_quantity', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('month_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_folders', to='backorders.expectedshippingmonthfolder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Expected Shipping Product',
                'verbose_name_plural': 'Expected Shipping Products',
                'ordering': ['month_folder__sort_order', 'product_code'],
                'unique_together': {('month_folder', 'product_code')},
            },
        ),
    ]
