# Generated by Django 5.2.15 on 2026-10-06 11:07

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('products', '0012_link_unlinked_factory_nodes_with_unique_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='科室名称')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_departments', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HospitalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('contact_type', models.CharField(choices=[('doctor', '医生'), ('purchasing', '采购人员'), ('admin', '行政人员'), ('nurse', '护士'), ('other', '其他联系人')], default='other', max_length=20, verbose_name='联系人类型')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='职位')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='电话')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_contacts', to='hospitals.hospital')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='hospital_engagements.hospitaldepartment', verbose_name='科室')),
            ],
            options={
                'ordering': ['-is_primary', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HospitalEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('stage_1', '第一阶段 · 未接触'), ('stage_2', '第二阶段 · 接触中'), ('stage_3', '第三阶段 · 落地中')], default='stage_1', max_length=20, verbose_name='阶段')),
                ('priority', models.CharField(choices=[('A', 'A · 高'), ('B', 'B · 中'), ('C', 'C · 低')], default='B', max_length=1, verbose_name='优先级')),
                ('demand_summary', models.TextField(blank=True, verbose_name='需求摘要')),
                ('special_requirements', models.TextField(blank=True, verbose_name='特殊需求')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步')),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='下次跟进日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='hospitals.hospital')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_engagements', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'ordering': ['priority', 'hospital__name', 'pk'],
                'permissions': [('access_hospital_engagement', 'Can access Hospital Engagement')],
            },
        ),
        migrations.CreateModel(
            name='HospitalFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('communication', '沟通记录'), ('stage_change', '阶段变更'), ('note', '备注')], default='communication', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='沟通时间')),
                ('channel', models.CharField(blank=True, choices=[('phone', '电话'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('visit', '拜访'), ('meeting', '会议'), ('other', '其他')], max_length=20, verbose_name='沟通方式')),
                ('summary', models.TextField(blank=True, verbose_name='沟通内容')),
                ('outcome', models.TextField(blank=True, verbose_name='沟通结果')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步')),
                ('next_follow_up_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('stage_from', models.CharField(blank=True, choices=[('stage_1', '第一阶段 · 未接触'), ('stage_2', '第二阶段 · 接触中'), ('stage_3', '第三阶段 · 落地中')], max_length=20)),
                ('stage_to', models.CharField(blank=True, choices=[('stage_1', '第一阶段 · 未接触'), ('stage_2', '第二阶段 · 接触中'), ('stage_3', '第三阶段 · 落地中')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='hospital_engagements.hospitalcontact', verbose_name='联系人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='hospital_engagements.hospitaldepartment', verbose_name='科室')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='hospital_engagements.hospitalengagement')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HospitalProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_text', models.CharField(blank=True, max_length=500, verbose_name='自由文本需求')),
                ('notes', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_interests', to='hospital_engagements.hospitaldepartment', verbose_name='科室')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interests', to='hospital_engagements.hospitalengagement')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_interests', to='products.product', verbose_name='产品')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='hospitaldepartment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('hospital'), condition=models.Q(('is_active', True)), name='he_active_department_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='hospitalcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('hospital',), name='he_one_active_primary_contact'),
        ),
        migrations.AddIndex(
            model_name='hospitalengagement',
            index=models.Index(fields=['stage', 'priority'], name='he_stage_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalfollowup',
            index=models.Index(fields=['engagement', 'activity_type', '-occurred_at'], name='he_latest_communication_idx'),
        ),
    ]
