# Generated by Django 5.2.15 on 2026-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_factorypurchaseorderdocument_hospitalinvoicedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('hospital_invoice', 'Hospital Invoice'), ('factory_po', 'Factory Purchase Order'), ('factory_order_request', 'Factory Order Request')], max_length=50),
        ),
    ]
