# Generated by Django 5.2.15 on 2026-10-07 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentsequence_payment_due_date_and_more'),
        ('orders', '0012_order_order_date'),
        ('shipments', '0006_shipmentbatch_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('hospital_invoice', 'Hospital Invoice'), ('factory_po', 'Factory Purchase Order'), ('factory_order_request', 'Factory Order Request'), ('commercial_po', 'Commercial Purchase Order')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'commercial_po')), fields=('shipment_batch',), name='unique_commercial_po_batch'),
        ),
    ]
