# Generated by Django 5.2.15 on 2026-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extracted_at',
            field=models.DateTimeField(blank=True, help_text='医院订单提取完成时间。', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extracted_order_data',
            field=models.JSONField(blank=True, help_text='医院订单 OCR 提取后的结构化 JSON 数据。', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extraction_error',
            field=models.TextField(blank=True, help_text='如果医院订单提取失败，在这里保存错误信息。'),
        ),
        migrations.AddField(
            model_name='order',
            name='extraction_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('success', 'Success'), ('failed', 'Failed')], default='not_started', help_text='医院订单 OCR / extraction 状态。', max_length=30),
        ),
    ]
