# Generated by Django 5.2.15 on 2026-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_hospital_match_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_validation_data',
            field=models.JSONField(blank=True, help_text='生成文件前的校验结果，包括 errors 和 warnings。', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='document_validation_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('ready', 'Ready'), ('needs_review', 'Needs review'), ('blocked', 'Blocked')], default='not_checked', help_text='生成 Invoice / PO 前的校验状态。', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='最后一次生成文件前校验时间。', null=True),
        ),
    ]
