# Generated by Django 5.2.15 on 2026-06-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backorders', '0001_initial'),
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('orders', '0007_orderitem_expiration_discount_rate_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backorderrootfolder',
            name='code',
            field=models.CharField(choices=[('backorder_orders', '待发产品'), ('expected_shipping', '预计可发产品'), ('inventory_products', '库存产品')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, default='', help_text='例如：SINOMED 2026-09 生产批次', max_length=200, verbose_name='库存批次名称')),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='inventory_batches/', verbose_name='工厂 Serial Number 文件')),
                ('batch_date', models.DateField(blank=True, help_text='可以理解为工厂发货日期或生产批次日期。', null=True, verbose_name='库存批次日期')),
                ('extraction_status', models.CharField(choices=[('pending', '待提取'), ('success', '提取成功'), ('failed', '提取失败')], default='pending', max_length=20, verbose_name='提取状态')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='提取结果')),
                ('extraction_error', models.TextField(blank=True, default='', verbose_name='提取错误')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to='factories.factory', verbose_name='工厂')),
            ],
            options={
                'verbose_name': '库存批次',
                'verbose_name_plural': '库存批次',
                'ordering': ['-batch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100, verbose_name='产品号')),
                ('serial_number', models.CharField(db_index=True, help_text='Serial Number 全局唯一，防止重复入库或重复发货。', max_length=200, unique=True, verbose_name='Serial Number')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('status', models.CharField(choices=[('available', '可用'), ('reserved', '已预留'), ('allocated', '已分配'), ('cancelled', '作废')], default='available', max_length=20, verbose_name='库存状态')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='原始提取数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_inventory_items', to='orders.order', verbose_name='已分配订单')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backorders.inventorybatch', verbose_name='库存批次')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存 Serial',
                'verbose_name_plural': '库存 Serials',
                'ordering': ['product_code', 'expiration_date', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProductFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='产品号')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('cancelled_quantity', models.PositiveIntegerField(default=0)),
                ('earliest_expiration_date', models.DateField(blank=True, null=True, verbose_name='最早有效期')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='最后计算时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存产品',
                'verbose_name_plural': '库存产品',
                'ordering': ['product_code'],
            },
        ),
    ]
