# Generated by Django 5.2.15 on 2026-06-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backorders', '0002_alter_backorderrootfolder_code_inventorybatch_and_more'),
        ('orders', '0007_orderitem_expiration_discount_rate_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100, verbose_name='产品号')),
                ('quantity_requested', models.PositiveIntegerField(default=1, verbose_name='预留数量')),
                ('allocated_count', models.PositiveIntegerField(default=0, verbose_name='实际预留数量')),
                ('status', models.CharField(choices=[('reserved', '已预留'), ('shipment_created', '已生成发货批次'), ('cancelled', '已取消')], default='reserved', max_length=30, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_allocations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_allocations', to='orders.order', verbose_name='目标订单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存预留记录',
                'verbose_name_plural': '库存预留记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='backorders.inventoryallocation', verbose_name='库存预留记录'),
        ),
    ]
