# Generated by Django 5.2.15 on 2026-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='医院正式名称。', max_length=255, unique=True)),
                ('normalized_name', models.CharField(blank=True, db_index=True, help_text='用于模糊匹配的标准化名称。', max_length=255)),
                ('billing_address', models.TextField(blank=True, help_text='发票地址 / billing address。')),
                ('default_shipping_address', models.TextField(blank=True, help_text='默认收货地址。如果订单 PDF 里有收货地址，则优先使用订单 PDF。')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
