# Generated by Django 5.2.15 on 2026-06-09 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_billing_address_data_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_pdf', models.FileField(help_text='工厂发来的含 serial number 和有效期的确认文件。', upload_to='factory_confirmations/%Y/%m/')),
                ('extraction_status', models.CharField(choices=[('not_started', 'Not started'), ('success', 'Success'), ('failed', 'Failed')], default='not_started', max_length=30)),
                ('extracted_confirmation_data', models.JSONField(blank=True, help_text='工厂确认文件提取后的结构化 JSON 数据。', null=True)),
                ('extraction_error', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_date', models.DateField(blank=True, help_text='工厂文件中的 shipping date。', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_factory_confirmations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_confirmations', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100)),
                ('serial_number', models.CharField(db_index=True, max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, help_text='折扣率，例如 0.30 表示 30%。', max_digits=5)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_items', to='factory_confirmations.factoryconfirmation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_items', to='products.product')),
            ],
            options={
                'ordering': ['product_code', 'serial_number'],
                'unique_together': {('order', 'serial_number')},
            },
        ),
    ]
