# Generated by Django 5.2.15 on 2026-06-12 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_confirmations', '0002_factoryconfirmation_factory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryconfirmation',
            name='bon_de_commande_manual_confirmed',
            field=models.BooleanField(default=False, help_text='Use this when the factory confirmation has no bon de commande or a mismatched bon de commande, but a human confirmed it belongs to the linked order.', verbose_name='Bon de commande manually confirmed'),
        ),
        migrations.AddField(
            model_name='factoryconfirmation',
            name='bon_de_commande_manual_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manually confirmed at'),
        ),
        migrations.AddField(
            model_name='factoryconfirmation',
            name='bon_de_commande_manual_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Manually confirmed by'),
        ),
        migrations.AddField(
            model_name='factoryconfirmation',
            name='bon_de_commande_manual_note',
            field=models.TextField(blank=True, default='', verbose_name='Manual confirmation note'),
        ),
    ]
