# Generated by Django 5.2.15 on 2026-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_confirmations', '0003_factoryconfirmation_bon_de_commande_manual_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryconfirmation',
            name='confirmation_type',
            field=models.CharField(choices=[('initial', '首批发货'), ('replenishment', '补发货'), ('adjustment', '调整 / 特殊情况')], default='initial', help_text='首批发货、补发货或特殊调整。', max_length=30, verbose_name='发货类型'),
        ),
    ]
