# Generated by Django 5.2.15 on 2026-07-14 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_documentsequence_payment_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('receivable', '医院应收'), ('payable', '工厂应付')], db_index=True, editable=False, max_length=20, verbose_name='结算方向')),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=255, verbose_name='医院或工厂名称快照')),
                ('issue_date', models.DateField(db_index=True, verbose_name='开立日期')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='付款截止日期')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='币种')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='应收或应付金额')),
                ('status', models.CharField(choices=[('unpaid', '未付款'), ('partially_paid', '部分付款'), ('paid', '已结清'), ('overdue', '已逾期'), ('cancelled', '已取消')], db_index=True, default='unpaid', max_length=30, verbose_name='结算状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='结算备注')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='取消原因')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_settlement_accounts', to=settings.AUTH_USER_MODEL, verbose_name='取消操作人')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_account', to='documents.generateddocument', verbose_name='正式文档')),
            ],
            options={
                'verbose_name': '结算账户',
                'verbose_name_plural': '结算账户',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='收付款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='收付款金额')),
                ('method', models.CharField(choices=[('bank_transfer', '银行转账'), ('cheque', '支票'), ('card', '银行卡'), ('cash', '现金'), ('other', '其他')], default='bank_transfer', max_length=30, verbose_name='付款方式')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='银行参考号')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('posted', '有效'), ('reversed', '已冲销')], db_index=True, default='posted', max_length=20, verbose_name='流水状态')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='冲销时间')),
                ('reversal_reason', models.TextField(blank=True, default='', verbose_name='冲销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='冲销人')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='settlements.settlementaccount', verbose_name='结算账户')),
            ],
            options={
                'verbose_name': '收付款流水',
                'verbose_name_plural': '收付款流水',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='settlementaccount',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='settlement_original_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_transaction_amount_gt_zero'),
        ),
    ]
