# Generated by Django 5.2.15 on 2026-06-09 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_billing_address_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, help_text='格式：YYYY-MM，例如 2026-06。', max_length=7)),
                ('bon_de_commande', models.CharField(db_index=True, max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_key', 'sequence'],
                'unique_together': {('month_key', 'bon_de_commande'), ('month_key', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('hospital_invoice', 'Hospital Invoice'), ('factory_po', 'Factory Purchase Order')], max_length=50)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, upload_to='generated_documents/pdf/%Y/%m/')),
                ('html_file', models.FileField(blank=True, upload_to='generated_documents/html/%Y/%m/')),
                ('source_data', models.JSONField(blank=True, help_text='生成该文件时使用的数据快照。', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='orders.order')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
