# Generated by Django 5.2.15 on 2026-06-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPurchaseOrderDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Factory purchase order',
                'verbose_name_plural': 'Factory purchase orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.generateddocument',),
        ),
        migrations.CreateModel(
            name='HospitalInvoiceDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Hospital invoice',
                'verbose_name_plural': 'Hospital invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.generateddocument',),
        ),
    ]
