# Generated by Django 5.2.15 on 2026-06-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_generateddocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOrderRequestDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Factory Order Request',
                'verbose_name_plural': 'Factory Order Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.generateddocument',),
        ),
    ]
