# Generated by Django 5.2.15 on 2026-06-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_factoryorderrequestdocument'),
        ('shipments', '0005_shipmentbatch_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='shipment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='shipments.shipmentbatch', verbose_name='发货批次'),
        ),
    ]
