# Generated by Django 5.2.15 on 2026-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_generateddocument_shipment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='document_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='html_file',
            field=models.FileField(blank=True, max_length=500, upload_to='generated_documents/html/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, upload_to='generated_documents/pdf/%Y/%m/'),
        ),
    ]
