# Generated by Django 5.2.15 on 2026-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_generateddocument_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsequence',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款时间'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='payment_notes',
            field=models.TextField(blank=True, default='', verbose_name='付款备注'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款状态'),
        ),
    ]
