# Generated by Django 5.2.15 on 2026-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentsequence_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsequence',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='付款截止日期'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='payment_reminder_date',
            field=models.DateField(blank=True, help_text='自动计算：付款截止日期前 10 天。', null=True, verbose_name='提醒日期'),
        ),
    ]
