"""Translation of known Portal labels only; business values are untouched."""
import re

from django.utils.translation import gettext, gettext_lazy, gettext_noop


CHOICE_LABELS = {
    'Complete': gettext_lazy('已完成'),
    'Completed': gettext_lazy('已完成'),
    'Factory Order Request': gettext_lazy('Factory Order Request'),
    'Factory Purchase Order': gettext_lazy('Factory Purchase Order'),
    'Failed': gettext_lazy('失败'),
    'Hospital Invoice': gettext_lazy('Hospital Invoice'),
    'Manually confirmed': gettext_lazy('人工确认'),
    'Needs review': gettext_lazy('需要人工检查'),
    'Not checked': gettext_lazy('待检查'),
    'Not started': gettext_lazy('待提取'),
    'OK': gettext_lazy('已就绪'),
    'Open': gettext_lazy('待处理'),
    'Over shipped': gettext_lazy('超发'),
    'Overdue': gettext_lazy('已逾期'),
    'Partial': gettext_lazy('部分完成'),
    'Planned': gettext_lazy('已计划'),
    'Success': gettext_lazy('提取成功'),
    '人工记录': gettext_lazy('人工记录'),
    '作废': gettext_lazy('作废'),
    '其他': gettext_lazy('其他'),
    '医院应收': gettext_lazy('医院应收'),
    '可以生成文件': gettext_lazy('可以生成文件'),
    '可用': gettext_lazy('可用'),
    '工厂应付': gettext_lazy('工厂应付'),
    '工厂确认文件': gettext_lazy('工厂确认文件'),
    '已付款': gettext_lazy('已付款'),
    '已冲销': gettext_lazy('已冲销'),
    '已分配': gettext_lazy('已分配'),
    '已取消': gettext_lazy('已取消'),
    '已生成发货批次': gettext_lazy('已生成发货批次'),
    '已结清': gettext_lazy('已结清'),
    '已逾期': gettext_lazy('已逾期'),
    '已预留': gettext_lazy('已预留'),
    '库存产品': gettext_lazy('库存产品'),
    '库存分配': gettext_lazy('库存分配'),
    '待发产品': gettext_lazy('待发产品'),
    '待提取': gettext_lazy('待提取'),
    '提取失败': gettext_lazy('提取失败'),
    '提取成功': gettext_lazy('提取成功'),
    '支票': gettext_lazy('支票'),
    '有效': gettext_lazy('有效'),
    '未付款': gettext_lazy('未付款'),
    '现金': gettext_lazy('现金'),
    '禁止生成文件': gettext_lazy('禁止生成文件'),
    '补发货': gettext_lazy('补发货'),
    '调整 / 特殊情况': gettext_lazy('调整 / 特殊情况'),
    '部分付款': gettext_lazy('部分付款'),
    '银行卡': gettext_lazy('银行卡'),
    '银行转账': gettext_lazy('银行转账'),
    '需要人工检查': gettext_lazy('需要人工检查'),
    '预计可发产品': gettext_lazy('预计可发产品'),
    '首批发货': gettext_lazy('首批发货'),
}


def display_choice(label):
    return CHOICE_LABELS.get(label, label)


def display_choices(choices):
    return [(value, display_choice(label)) for value, label in choices]


# Only messages generated by Portal basic validation are recognized. Unknown
# OCR/upstream messages and user-entered text are returned verbatim.
VALIDATION_MESSAGES = (
    gettext_noop("Factory PO 定价要求 ShipmentBatch 关联 FactoryConfirmation 或 InventoryAllocation。"),
    gettext_noop('没有成功提取 bon de commande。'),
    gettext_noop('没有成功提取医院订单日期。'),
    gettext_noop('没有成功提取医院名称。'),
    gettext_noop('医院没有匹配到数据库记录。'),
    gettext_noop('没有提取到收货地址。'),
    gettext_noop('没有提取到账单地址。'),
    gettext_noop('没有提取到任何产品明细。'),
    gettext_noop('产品行 #%(product)s 没有产品号。'),
    gettext_noop('产品 %(product)s 没有匹配到产品库，请核对产品编码。'),
    gettext_noop('产品 %(product)s 的订单数量异常。'),
    gettext_noop('产品 %(product)s 缺少有效医院单价。'),
    gettext_noop('产品 %(product)s 尚未应用医院价格规则，请重新应用 PricePolicy。'),
    gettext_noop('产品 %(product)s 的产品编码待核对。'),
)


def display_validation_message(message):
    text = str(message)
    for source in VALIDATION_MESSAGES:
        if "%(product)s" in source:
            pattern = re.escape(source).replace(re.escape("%(product)s"), "(?P<product>.+)")
            match = re.fullmatch(pattern, text)
            if match:
                return gettext(source) % match.groupdict()
        elif source == text:
            return gettext(source)
    return message


# Labels supplied by the read-only finance dashboard service.
FINANCE_LABELS = (
    gettext_noop('医院已收金额'),
    gettext_noop('医院已收金额减去工厂已付金额。'),
    gettext_noop('医院应收原始金额减去有效收款。'),
    gettext_noop('医院开票销售额'),
    gettext_noop('医院开票销售额减去工厂采购额。'),
    gettext_noop('医院待收余额'),
    gettext_noop('实际现金净流入'),
    gettext_noop('工厂已付金额'),
    gettext_noop('工厂应付原始金额减去有效付款。'),
    gettext_noop('工厂待付余额'),
    gettext_noop('工厂采购额'),
    gettext_noop('截止日期早于今天且仍有余额的医院应收。'),
    gettext_noop('有效 Factory PO 结算账户原始金额合计。'),
    gettext_noop('有效医院 Invoice 结算账户原始金额合计。'),
    gettext_noop('有效医院收款流水合计。'),
    gettext_noop('有效工厂付款流水合计。'),
    gettext_noop('逾期应收金额'),
    gettext_noop('预计毛利润'),
    gettext_noop('预计毛利润除以医院开票销售额。'),
    gettext_noop('预计毛利率'),
)


# Model metadata used by Portal forms, translated without model changes.
FORM_HELP_TEXTS = (
    gettext_noop('产品库卡片和日常页面优先显示此简称。'),
    gettext_noop('产品描述。'),
    gettext_noop('产品编号，例如 BMA-2.2510。'),
    gettext_noop('从工厂采购的单价。'),
    gettext_noop('例如 365 表示距离有效期不足 365 天时应用临期折扣。'),
    gettext_noop('分类名称。'),
    gettext_noop('包含该日期。留空表示无下限。'),
    gettext_noop('包含该日期。留空表示长期有效。'),
    gettext_noop('医院正式名称。'),
    gettext_noop('卖给医院的单价。'),
    gettext_noop('发票地址 / billing address。'),
    gettext_noop('同一层级中的显示顺序，数字越小越靠前。'),
    gettext_noop('备注。'),
    gettext_noop('工厂地址。'),
    gettext_noop('工厂完整法律名称。'),
    gettext_noop('工厂正式名称。'),
    gettext_noop('建议包含工厂、分类和年份，例如：SINOMED 支架 2026。'),
    gettext_noop('是否启用。'),
    gettext_noop('每行填写一个关键词，例如简称、英文名、地址关键词。'),
    gettext_noop('生成 Factory Purchase Order 时使用的默认描述。'),
    gettext_noop('留空表示全局回退规则。'),
    gettext_noop('留空表示适用于所选工厂的全部产品。工厂也留空时表示全局回退规则。'),
    gettext_noop('输入 30 表示优惠 30%，即工厂最终按原采购价的 70% 结算。'),
    gettext_noop('采购联系人 / Buyer。'),
    gettext_noop('默认收货地址。如果订单 PDF 里有收货地址，则优先使用订单 PDF。'),
)
