# Generated by Django 5.2.15 on 2026-06-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_de_commande', models.CharField(help_text='医院订单号，例如 150222', max_length=100, unique=True)),
                ('hospital_name', models.CharField(blank=True, help_text='医院名称。Milestone 1 可手动填写；后续由 OCR 自动提取。', max_length=255)),
                ('hospital_order_pdf', models.FileField(help_text='医院发来的订单 PDF。', upload_to='hospital_orders/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hospital_order_uploaded', 'Hospital order uploaded'), ('extracted', 'Extracted'), ('confirmed', 'Confirmed'), ('documents_generated', 'Documents generated')], default='hospital_order_uploaded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
