# Generated by Django 5.2.15 on 2026-06-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('orders', '0002_order_extracted_at_order_extracted_order_data_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_data',
            field=models.JSONField(blank=True, help_text='订单中确认使用的账单地址。', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_order_data',
            field=models.JSONField(blank=True, help_text='人工确认后的订单数据。后续生成 Invoice / PO 应优先使用这个字段。', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='匹配到的医院数据库记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_data',
            field=models.JSONField(blank=True, help_text='订单中确认使用的收货地址。', null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, help_text='订单中提取到的产品编号。', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requested_quantity', models.PositiveIntegerField(default=0, help_text='医院订单请求数量。')),
                ('confirmed_quantity', models.PositiveIntegerField(default=0, help_text='工厂确认有货数量。')),
                ('backordered_quantity', models.PositiveIntegerField(default=0, help_text='缺货数量。')),
                ('hospital_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('partially_confirmed', 'Partially confirmed'), ('backordered', 'Backordered'), ('cancelled', 'Cancelled')], default='requested', max_length=50)),
                ('raw_data', models.JSONField(blank=True, help_text='该产品行的原始提取数据。', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, help_text='匹配到的产品数据库记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
