# Generated by Django 5.2.15 on 2026-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_billing_address_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hospital_match_message',
            field=models.TextField(blank=True, help_text='医院匹配说明。如果需要人工确认，会写在这里。'),
        ),
        migrations.AddField(
            model_name='order',
            name='hospital_match_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('ok', 'OK'), ('needs_review', 'Needs review'), ('manually_confirmed', 'Manually confirmed')], default='not_checked', help_text='医院数据库匹配状态。', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_manually_confirmed',
            field=models.BooleanField(default=False, help_text='人工确认该产品行无误后勾选。'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_match_message',
            field=models.TextField(blank=True, help_text='产品匹配说明。如果需要人工确认，会写在这里。'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_match_status',
            field=models.CharField(choices=[('ok', 'OK'), ('needs_review', 'Needs review'), ('manually_confirmed', 'Manually confirmed')], default='needs_review', help_text='产品编号和产品库的匹配状态。', max_length=50),
        ),
    ]
