# Generated by Django 5.2.15 on 2026-06-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_factory_order_factory_match_message_and_more'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expiration_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Example: 0.30 means 30% discount, i.e. 70% final price.', max_digits=5, null=True, verbose_name='Expiration discount rate snapshot'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='factory_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Factory unit price snapshot'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pricing.pricepolicy', verbose_name='Applied price policy'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_policy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Price policy date'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_policy_message',
            field=models.TextField(blank=True, default='', verbose_name='Price policy message'),
        ),
    ]
