# Generated by Django 5.2.15 on 2026-07-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expiration_threshold_days',
            field=models.PositiveIntegerField(blank=True, help_text='临期折扣门槛天数快照。正式 PO 不应重新读取当前 PricePolicy。', null=True, verbose_name='Expiration threshold days snapshot'),
        ),
    ]
