# Generated by Django 5.2.15 on 2026-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='工厂正式名称。', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='简称，例如 Sino Medical。', max_length=100)),
                ('address', models.TextField(blank=True, help_text='工厂地址。')),
                ('buyer', models.CharField(blank=True, help_text='采购联系人 / Buyer。', max_length=255)),
                ('default_product_description', models.CharField(blank=True, help_text='生成工厂 PO 时的默认产品描述。', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用。')),
                ('notes', models.TextField(blank=True, help_text='备注。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
            },
        ),
    ]
