# Generated by Django 5.2.15 on 2026-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='legal_name',
            field=models.CharField(blank=True, help_text='工厂完整法律名称。', max_length=255),
        ),
        migrations.AddField(
            model_name='factory',
            name='match_keywords',
            field=models.TextField(blank=True, help_text='用于自动匹配的关键词，每行一个。例如工厂简称、英文名、地址关键词。'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='default_product_description',
            field=models.CharField(blank=True, default='HT-Supreme™ Drug Eluting Stent', help_text='生成工厂 PO 时的默认产品描述。', max_length=255),
        ),
        migrations.AlterField(
            model_name='factory',
            name='short_name',
            field=models.CharField(blank=True, help_text='简称，例如 LEPU MEDICAL。', max_length=100),
        ),
    ]
