# Generated by Django 5.2.15 on 2026-06-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_factory_order_factory_match_message_and_more'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipment Month',
                'verbose_name_plural': 'Shipment Batches',
                'ordering': ['-month_key'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrderFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_folders', to='shipments.shipmentmonth')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_order_folders', to='orders.order')),
            ],
            options={
                'verbose_name': 'Shipment Order Folder',
                'verbose_name_plural': 'Shipment Order Folders',
                'ordering': ['-month__month_key', 'order__bon_de_commande'],
                'unique_together': {('month', 'order')},
            },
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='order_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shipments.shipmentorderfolder'),
        ),
    ]
