# Generated by Django 5.2.15 on 2026-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipmentbatch_factory_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbatch',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='校验时间'),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='validation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='校验结果'),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='validation_status',
            field=models.CharField(choices=[('ready', '可以生成文件'), ('needs_review', '需要人工检查'), ('blocked', '禁止生成文件')], default='needs_review', max_length=30, verbose_name='校验状态'),
        ),
    ]
