# Generated by Django 5.2.15 on 2026-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productbrowsercategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='factory_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='从工厂采购的单价。', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hospital_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='卖给医院的单价。', max_digits=10, null=True),
        ),
    ]
