# Generated by Django 5.2.15 on 2026-07-13 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_factory_legal_name_factory_match_keywords_and_more'),
        ('products', '0007_alter_product_factory_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['parent__name', 'sort_order', 'name'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='仅工厂节点使用。关联到真实 Factory 记录，避免仅依赖工厂名称进行匹配。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category_nodes', to='factories.factory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='node_type',
            field=models.CharField(choices=[('department', '科室'), ('factory', '工厂'), ('category', '产品分类')], db_index=True, default='category', help_text='该节点在产品库中的层级类型。', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='同一层级中的显示顺序，数字越小越靠前。'),
        ),
    ]
