# Generated by Django 5.2.15 on 2026-07-13 06:04

from django.db import migrations

def normalize_name(value):
    """
    工厂名称比较时忽略：
    - 大小写
    - 空格
    - 标点符号

    例如：
        "LEPU MEDICAL"
        "Lepu-Medical"
    会得到相近的规范化结果。
    """
    text = str(value or "").casefold()
    return "".join(char for char in text if char.isalnum())


def classify_product_category_nodes(apps, schema_editor):
    ProductCategory = apps.get_model(
        "products",
        "ProductCategory",
    )
    Factory = apps.get_model(
        "factories",
        "Factory",
    )

    # 第一级：没有 parent 的节点是科室。
    ProductCategory.objects.filter(
        parent__isnull=True,
    ).update(
        node_type="department",
    )

    # 第二级：parent 是一级节点的记录是工厂入口。
    ProductCategory.objects.filter(
        parent__isnull=False,
        parent__parent__isnull=True,
    ).update(
        node_type="factory",
    )

    # 第三级及更深层：产品分类。
    ProductCategory.objects.filter(
        parent__isnull=False,
        parent__parent__isnull=False,
    ).update(
        node_type="category",
    )

    # 构造真实 Factory 名称索引。
    factory_lookup = {}

    for factory in Factory.objects.all():
        possible_names = [
            getattr(factory, "name", ""),
            getattr(factory, "short_name", ""),
            getattr(factory, "legal_name", ""),
        ]

        for possible_name in possible_names:
            normalized = normalize_name(possible_name)

            if not normalized:
                continue

            factory_lookup.setdefault(normalized, [])

            if factory.pk not in [
                item.pk for item in factory_lookup[normalized]
            ]:
                factory_lookup[normalized].append(factory)

    # 将第二级“工厂文件夹”关联到真实 Factory。
    factory_nodes = ProductCategory.objects.filter(
        node_type="factory",
        factory__isnull=True,
    )

    for node in factory_nodes:
        normalized_node_name = normalize_name(node.name)
        matches = factory_lookup.get(normalized_node_name, [])

        # 只有唯一匹配时才自动关联。
        if len(matches) == 1:
            node.factory_id = matches[0].pk
            node.save(update_fields=["factory"])


def reverse_classification(apps, schema_editor):
    ProductCategory = apps.get_model(
        "products",
        "ProductCategory",
    )

    ProductCategory.objects.all().update(
        node_type="category",
        factory=None,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            classify_product_category_nodes,
            reverse_classification,
        ),
    ]
